* pytest.el

`pytest.el` provides a set of functions that handle running pytest on a
particular buffer or part of a buffer.  This started as a direct
port of nosemacs (https://bitbucket.org/durin42/nosemacs).  A
special thanks to Jason Pellerin and Augie Fackler for writing
nose.el.

** Installation

In your Emacs config:

#+BEGIN_SRC elisp
  (require 'pytest)
#+END_SRC

If you don't use a global installation of pytest (ie in
virtualenv) then add something like the following that points to
either the non-global version or a test runner script.

#+BEGIN_SRC elisp
  (add-to-list 'pytest-project-names "my/crazy/runner")
#+END_SRC

For example, you can generate a script with pytest:

#+BEGIN_SRC sh
  pytest --genscript=run-tests.py
#+END_SRC

A much better pattern is to use a `.dir-locals.el` file to define the
test runner executable. For example, I use a small library called [[https://github.com/ionrock/xe][xe]]
for finding the current project's virtualenv. Here is what
`.dir-locals.el` would look like, using xe.

#+BEGIN_SRC elisp
  ;;; Directory Local Variables
  ;;; For more information see (info "(emacs) Directory Variables")

  ((python-mode
    (pytest-global-name . "xe test")
    (pytest-cmd-flags . "")))
#+END_SRC

By default, the root of a project is found by looking for any of the files
'setup.py', '.hg' and '.git'.  You can add files to check for to the file
list:

#+BEGIN_SRC elisp
 (add-to-list 'pytest-project-root-files ".bzr")
#+END_SRC

You can also change the project root test to detect in some other way
whether a directory is the project root:

#+BEGIN_SRC elisp
  (setq pytest-project-root-test (lambda (dirname) (equal dirname "foo")))
#+END_SRC

By default, test paths passed to pytest are absolute paths:
#+BEGIN_SRC sh
  cd /project/root && pytest /project/root/path/to/test.py
#+END_SRC

To override this behavior, set an optional base path that will be stripped from test path arguments:
#+BEGIN_SRC elisp
  (setq pytest-relative-test-paths "/project/root/")
#+END_SRC

which will set test paths relative to that base path:
#+BEGIN_SRC sh
   cd /project/root && pytest path/to/test.py
#+END_SRC

This will enable individual tests to run correctly in containers that map to different working directories:
#+BEGIN_SRC elisp
;;; Example dir-locals.el:
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((python-mode
  (pytest-global-name . "docker-compose run --rm app pytest")
  (pytest-cmd-flags . "")
  (pytest-relative-test-paths . "/base/path/")))
#+END_SRC

An example of why you'd want to apply relative test path arguments is running tests in a docker compose environment for an app that contains multiple sub-projects and those tests are contained within a mounted volume that is a subdirectory of the project root:
#+BEGIN_SRC shell
  # project root
  /project/root/
  # local app directory
  /project/root/app
  # corresponding container app directory mounted in container
  /opt/app
  # default full test path outside of container
  /project/root/app/path/to/test.py
#+END_SRC
In that case, running the default command in the container will fail since it does not take into account the container directory structure:
#+BEGIN_SRC sh
    cd /path/to/project/root && docker-compose run --rm app pytest /path/to/docker/mount/volume/relative/path/to/test.py
#+END_SRC

but passing in a relative test path should run:
#+BEGIN_SRC sh
  cd /path/to/project/root && docker-compose run --rm app pytest relative/path/to/test.py
#+END_SRC

** Key bindings

Here are some suggested keybindings for running the tests within your
python-mode buffers.

#+BEGIN_SRC elisp
  (add-hook 'python-mode-hook
            (lambda ()
              (local-set-key "\C-ca" 'pytest-all)
              (local-set-key "\C-cm" 'pytest-module)
              (local-set-key "\C-c." 'pytest-one)
              (local-set-key "\C-cc" 'pytest-again)
              (local-set-key "\C-cd" 'pytest-directory)
              (local-set-key "\C-cpa" 'pytest-pdb-all)
              (local-set-key "\C-cpm" 'pytest-pdb-module)
              (local-set-key "\C-cp." 'pytest-pdb-one)))
#+END_SRC
